### ISSUE TITLE
Laravel and Bootflat

### ISSUE THREAD

**Issue by myrrec** [bootflat/bootflat.github.io#84]
Hello. I am using Laravel 5 and Bootflat(last version).  The Bootflat file is loaded as link rel="stylesheet" but everything remains as it was. What's the problem?
![2015-05-24 16-18-10](https://cloud.githubusercontent.com/assets/7099650/7787971/d8d87328-0238-11e5-9726-91e90851d5b7.png)

**Comment by lindelius** [comment]
It might be because you're including Bootstrap after Bootflat.

Try
```html
<link rel="stylesheet" href="/local/storage/app/system/css/all/bootstrap.min.css" />
<link rel="stylesheet" href="/local/storage/app/system/css/all/bootflat.css" />
```
